Dev-13564 Implement shortcuts for inserting a comment, global comment and change proposal
FontoXML/fontoxml-review-reference-configuration pull request #25
Opened 2022-04-08 07:37 UTC by sergiovp

2022-04-12 08:07 UTC, ThomasBrekelmans requested changes

2022-04-12 08:07 UTC, ThomasBrekelmans commented on src/install.ts
> +const OS_KEY = navigator.userAgent.includes('Mac') ? 'Cmd' : 'Ctrl';
We use the command symbol ⌘ here by convention in Fonto (instead of 'Cmd')

2022-04-13 07:42 UTC, ThomasBrekelmans approved these changes
Previously requested changes no longer apply. PR is ready for integration AFAIC.

2022-04-26 15:42 UTC, albertosml approved these changes

2022-04-28 10:21 UTC, merged